name: dart_hooks
description: Automating the integration and management of Git Hooks in Dart projects
version: 1.0.3
repository: https://github.com/errorempire/DartHooks
homepage: https://github.com/errorempire/DartHooks
documentation: https://github.com/errorempire/DartHooks/blob/main/README.md
issue_tracker: https://github.com/errorempire/DartHooks/issues

environment:
  sdk: ^3.0.4

executables:
  init:
  pre_commit:
  pre_push:
  apply:
  destroy:

dependencies:
  json2yaml: ^3.0.1
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.0.0
